[workspace]
members = [
    "ore",
    "repr",
    "sql-parser",
    "edna",
    "edna-srv",
    "lobsters-decay",
    "applications/hotcrp",
    "applications/lobsters",
    "applications/websubmit-rs",
]
