#!/usr/bin/env ruby

APP_PATH = File.expand_path('../../config/application', __FILE__)
require File.expand_path('../../config/boot', __FILE__)
require APP_PATH
require 'swagger_client'
Rails.application.require_environment!

User.inactive.each_with_index do |u, x|
    uid = @u.id.to_s
    api_instance = SwaggerClient::DefaultApi.new
    body = SwaggerClient::ApplyDisguise.new() # ApplyDisguise |
    body.decrypt_cap = Base64.decode64(params[:user][:pkey]).bytes
    body.locators = []
    gdpr_disguise = File.read("disguises/gdpr_disguise.json")
    body.disguise_json = gdpr_disguise.gsub('UID', uid)
    body.tableinfo_json = File.read("disguises/table_info.json")

    begin
      result = api_instance.apiproxy_apply_disguise(body)
      # get locator of user (XXX note that only one user's locator is returned..)
      locator = JSON.dump(result.locators.values[0])
      did = result.did

      p locator
      p did 
      DecayNotification.notify(@user, locator, did).deliver_now
    rescue SwaggerClient::ApiError => e
      puts "Exception when calling DefaultApi->apiproxy_apply_disguise: #{e}"
    end
end
