#!/usr/bin/env ruby

APP_PATH = File.expand_path('../../config/application', __FILE__)
require File.expand_path('../../config/boot', __FILE__)
require APP_PATH
require 'swagger_client'
Rails.application.require_environment!

User.inactive.each_with_index do |u, x|
    uid = @u.id.to_s
    api_instance = SwaggerClient::DefaultApi.new
    body = SwaggerClient::ApplyDisguise.new() # ApplyDisguise |
    body.user = uid
    body.password = "" # No composition for decay
    body.locators = []
    gdpr_disguise_json = File.read("disguises/gdpr_disguise.json")
    body.tableinfo_json = File.read("disguises/table_info.json")
    body.guisegen_json = File.read("disguises/guise_gen.json")

    begin
      result = api_instance.apiproxy_apply_disguise(body)
      locator = JSON.dump(result.locators.values[0])
      did = result.did

      p locator
      p did 
      DecayNotification.notify(@user, locator, did).deliver_now
    rescue SwaggerClient::ApiError => e
      puts "Exception when calling DefaultApi->apiproxy_apply_disguise: #{e}"
    end
end
