CREATE VIEW ReviewRating0 AS SELECT `paperId` AS `paperId`, `reviewId` AS `reviewId`, rating AS rating, 0 AS `contactId` FROM `ReviewRating` WHERE `contactId` = 29 UNION SELECT * FROM `ReviewRating` WHERE `contactId` <> 29

CREATE TEMPORARY TABLE ReviewRatingTemp AS SELECT `paperId` AS `paperId`, `reviewId` AS `reviewId`, rating AS rating, 0 AS `contactId` FROM `ReviewRating0`

CREATE VIEW PaperReviewPreference0 AS SELECT * FROM `PaperReviewPreference` WHERE `contactId` <> 29

CREATE TEMPORARY TABLE PaperReviewPreferenceTemp AS SELECT `paperId` AS `paperId`, preference AS preference, expertise AS expertise, 0 AS `contactId` FROM `PaperReviewPreference0`

CREATE VIEW PaperComment0 AS SELECT `paperId` AS `paperId`, `commentId` AS `commentId`, `timeModified` AS `timeModified`, `timeNotified` AS `timeNotified`, `timeDisplayed` AS `timeDisplayed`, comment AS comment, `commentType` AS `commentType`, `replyTo` AS `replyTo`, ordinal AS ordinal, `authorOrdinal` AS `authorOrdinal`, `commentTags` AS `commentTags`, `commentRound` AS `commentRound`, `commentFormat` AS `commentFormat`, `commentOverflow` AS `commentOverflow`, 0 AS `contactId` FROM `PaperComment` WHERE `contactId` = 29 UNION SELECT * FROM `PaperComment` WHERE `contactId` <> 29

CREATE TEMPORARY TABLE PaperCommentTemp AS SELECT `paperId` AS `paperId`, `commentId` AS `commentId`, `timeModified` AS `timeModified`, `timeNotified` AS `timeNotified`, `timeDisplayed` AS `timeDisplayed`, comment AS comment, `commentType` AS `commentType`, `replyTo` AS `replyTo`, ordinal AS ordinal, `authorOrdinal` AS `authorOrdinal`, `commentTags` AS `commentTags`, `commentRound` AS `commentRound`, `commentFormat` AS `commentFormat`, `commentOverflow` AS `commentOverflow`, 0 AS `contactId` FROM `PaperComment0`

CREATE VIEW PaperReview0 AS SELECT `paperId` AS `paperId`, `reviewId` AS `reviewId`, `reviewToken` AS `reviewToken`, `reviewType` AS `reviewType`, `reviewRound` AS `reviewRound`, `timeRequested` AS `timeRequested`, `timeRequestNotified` AS `timeRequestNotified`, `reviewBlind` AS `reviewBlind`, `reviewModified` AS `reviewModified`, `reviewAuthorModified` AS `reviewAuthorModified`, `reviewSubmitted` AS `reviewSubmitted`, `reviewNotified` AS `reviewNotified`, `reviewAuthorNotified` AS `reviewAuthorNotified`, `reviewAuthorSeen` AS `reviewAuthorSeen`, `reviewOrdinal` AS `reviewOrdinal`, `reviewViewScore` AS `reviewViewScore`, `timeDisplayed` AS `timeDisplayed`, `timeApprovalRequested` AS `timeApprovalRequested`, `reviewEditVersion` AS `reviewEditVersion`, `reviewNeedsSubmit` AS `reviewNeedsSubmit`, `reviewWordCount` AS `reviewWordCount`, `reviewFormat` AS `reviewFormat`, `overAllMerit` AS `overAllMerit`, `reviewerQualification` AS `reviewerQualification`, novelty AS novelty, `technicalMerit` AS `technicalMerit`, `interestToCommunity` AS `interestToCommunity`, longevity AS longevity, grammar AS grammar, `likelyPresentation` AS `likelyPresentation`, `suitableForShort` AS `suitableForShort`, potential AS potential, fixability AS fixability, tfields AS tfields, sfields AS sfields, data AS data, 0 AS `contactId`, 0 AS `requestedBy` FROM `PaperReview` WHERE `contactId` = 29 OR `requestedBy` = 29 UNION SELECT * FROM `PaperReview` WHERE `contactId` <> 29 AND `requestedBy` <> 29

CREATE TEMPORARY TABLE PaperReviewTemp AS SELECT `paperId` AS `paperId`, `reviewId` AS `reviewId`, `reviewToken` AS `reviewToken`, `reviewType` AS `reviewType`, `reviewRound` AS `reviewRound`, `timeRequested` AS `timeRequested`, `timeRequestNotified` AS `timeRequestNotified`, `reviewBlind` AS `reviewBlind`, `reviewModified` AS `reviewModified`, `reviewAuthorModified` AS `reviewAuthorModified`, `reviewSubmitted` AS `reviewSubmitted`, `reviewNotified` AS `reviewNotified`, `reviewAuthorNotified` AS `reviewAuthorNotified`, `reviewAuthorSeen` AS `reviewAuthorSeen`, `reviewOrdinal` AS `reviewOrdinal`, `reviewViewScore` AS `reviewViewScore`, `timeDisplayed` AS `timeDisplayed`, `timeApprovalRequested` AS `timeApprovalRequested`, `reviewEditVersion` AS `reviewEditVersion`, `reviewNeedsSubmit` AS `reviewNeedsSubmit`, `reviewWordCount` AS `reviewWordCount`, `reviewFormat` AS `reviewFormat`, `overAllMerit` AS `overAllMerit`, `reviewerQualification` AS `reviewerQualification`, novelty AS novelty, `technicalMerit` AS `technicalMerit`, `interestToCommunity` AS `interestToCommunity`, longevity AS longevity, grammar AS grammar, `likelyPresentation` AS `likelyPresentation`, `suitableForShort` AS `suitableForShort`, potential AS potential, fixability AS fixability, tfields AS tfields, sfields AS sfields, data AS data, 0 AS `contactId`, 0 AS `requestedBy` FROM `PaperReview0`

CREATE TEMPORARY TABLE PaperConflictTemp AS SELECT * FROM `PaperConflict` WHERE `contactId` <> 29

CREATE VIEW ContactInfo0 AS SELECT * FROM `ContactInfo` WHERE `contactId` <> 29

CREATE TEMPORARY TABLE ContactInfoTemp AS SELECT `contactId` AS `contactId`, `firstName` AS `firstName`, `lastName` AS `lastName`, `unaccentedName` AS `unaccentedName`, `preferredEmail` AS `preferredEmail`, affiliation AS affiliation, phone AS phone, country AS country, password AS password, `passwordTime` AS `passwordTime`, `passwordUseTime` AS `passwordUseTime`, collaborators AS collaborators, `creationTime` AS `creationTime`, `updateTime` AS `updateTime`, `lastLogin` AS `lastLogin`, `defaultWatch` AS `defaultWatch`, roles AS roles, disabled AS disabled, `contactTags` AS `contactTags`, birthday AS birthday, gender AS gender, data AS data, `isGuise` AS `isGuise`, 'anonymousrfkbfTxBns7R@secret.mail' AS email FROM `ContactInfo0`

CREATE TEMPORARY TABLE TopicInterestTemp AS SELECT * FROM `TopicInterest` WHERE `contactId` <> 29

CREATE VIEW ActionLog0 AS SELECT `logId` AS `logId`, `paperId` AS `paperId`, timestamp AS timestamp, ipaddr AS ipaddr, action AS action, data AS data, 0 AS `contactId`, 0 AS `destContactId`, 0 AS `trueContactId` FROM `ActionLog` WHERE `contactId` = 29 OR `destContactId` = 29 OR `trueContactId` = 29 UNION SELECT * FROM `ActionLog` WHERE `contactId` <> 29 AND `destContactId` <> 29 AND `trueContactId` <> 29

CREATE TEMPORARY TABLE ActionLogTemp AS SELECT `logId` AS `logId`, `paperId` AS `paperId`, timestamp AS timestamp, ipaddr AS ipaddr, action AS action, data AS data, 0 AS `contactId`, 0 AS `destContactId`, 0 AS `trueContactId` FROM `ActionLog0`

CREATE VIEW PaperReviewRefused0 AS SELECT `paperId` AS `paperId`, email AS email, `firstName` AS `firstName`, `lastName` AS `lastName`, affiliation AS affiliation, `contactId` AS `contactId`, `timeRequested` AS `timeRequested`, `timeRefused` AS `timeRefused`, `reviewType` AS `reviewType`, `reviewRound` AS `reviewRound`, data AS data, reason AS reason, 0 AS `requestedBy`, 0 AS `refusedBy` FROM `PaperReviewRefused` WHERE `requestedBy` = 29 OR `refusedBy` = 29 UNION SELECT * FROM `PaperReviewRefused` WHERE `requestedBy` <> 29 AND `refusedBy` <> 29

CREATE TEMPORARY TABLE PaperReviewRefusedTemp AS SELECT `paperId` AS `paperId`, email AS email, `firstName` AS `firstName`, `lastName` AS `lastName`, affiliation AS affiliation, `contactId` AS `contactId`, `timeRequested` AS `timeRequested`, `timeRefused` AS `timeRefused`, `reviewType` AS `reviewType`, `reviewRound` AS `reviewRound`, data AS data, reason AS reason, 0 AS `requestedBy`, 0 AS `refusedBy` FROM `PaperReviewRefused0`

CREATE VIEW Paper0 AS SELECT `paperId` AS `paperId`, title AS title, `authorInformation` AS `authorInformation`, abstract AS abstract, collaborators AS collaborators, `timeSubmitted` AS `timeSubmitted`, `timeWithdrawn` AS `timeWithdrawn`, `timeFinalSubmitted` AS `timeFinalSubmitted`, `timeModified` AS `timeModified`, `paperStorageId` AS `paperStorageId`, sha1 AS sha1, `finalPaperStorageId` AS `finalPaperStorageId`, blind AS blind, outcome AS outcome, `capVersion` AS `capVersion`, size AS size, mimetype AS mimetype, timestamp AS timestamp, `pdfFormatStatus` AS `pdfFormatStatus`, `withdrawReason` AS `withdrawReason`, `paperFormat` AS `paperFormat`, `dataOverflow` AS `dataOverflow`, 0 AS `leadContactId`, 0 AS `shepherdContactId`, 0 AS `managerContactId` FROM `Paper` WHERE `leadContactId` = 29 OR `shepherdContactId` = 29 OR `managerContactId` = 29 UNION SELECT * FROM `Paper` WHERE `leadContactId` <> 29 AND `shepherdContactId` <> 29 AND `managerContactId` <> 29

CREATE TEMPORARY TABLE PaperTemp AS SELECT `paperId` AS `paperId`, title AS title, `authorInformation` AS `authorInformation`, abstract AS abstract, collaborators AS collaborators, `timeSubmitted` AS `timeSubmitted`, `timeWithdrawn` AS `timeWithdrawn`, `timeFinalSubmitted` AS `timeFinalSubmitted`, `timeModified` AS `timeModified`, `paperStorageId` AS `paperStorageId`, sha1 AS sha1, `finalPaperStorageId` AS `finalPaperStorageId`, blind AS blind, outcome AS outcome, `capVersion` AS `capVersion`, size AS size, mimetype AS mimetype, timestamp AS timestamp, `pdfFormatStatus` AS `pdfFormatStatus`, `withdrawReason` AS `withdrawReason`, `paperFormat` AS `paperFormat`, `dataOverflow` AS `dataOverflow`, 0 AS `leadContactId`, 0 AS `shepherdContactId`, 0 AS `managerContactId` FROM `Paper0`

CREATE TEMPORARY TABLE CapabilityTemp AS SELECT * FROM `Capability` WHERE `contactId` <> 29

CREATE VIEW PaperWatch0 AS SELECT * FROM `PaperWatch` WHERE `contactId` <> 29

CREATE TEMPORARY TABLE PaperWatchTemp AS SELECT `paperId` AS `paperId`, watch AS watch, 0 AS `contactId` FROM `PaperWatch0`

